# Let travis know the language it needs to run
#sudo: false


# Mention the python version in which travis will run the app
python:
  - "3.6"

os: osx

compiler:
 - gcc

language:
  #- cpp
  - python

script:
  - ./totravis.sh
 # - pytest

notifications:
  email: false
