# Let travis know the language it needs to run
#sudo: false


# Mention the python version in which travis will run the app
python:
  - 3.6
matrix:
  include:
    - python: 3.6  #- python: 3.7
      dist: xenial
      sudo: true

os: osx


language:
  #- cpp
  - python
before_install:
  - ./install.sh
script:
  #- ./install.sh
  - ./totravis.sh
  - pytest

notifications:
  email: false
